### ISSUE TITLE
Incomplete sentences in example documentation

### ISSUE THREAD

**Issue by dietmarw** [MarekMatejak/Chemical#18]
I just read through the documentation of `Chemical.Examples.EnzymeKinetics` and the last paragraph is a stub:

> ### The increasing of the amount of the enzyme
> In the situation of doubled amount of enzyme should double also the maximal speed of the reaction, shouldn't?
> The assumptions of

**Comment by MarekMatejak** [comment]
Hello Dietmar,
I solved this documentation by removing this incomplete section. Please note, that this example is only ilustrational explanation of widely used Michaelis-Menton simplification. May be in future there will be much better to include more specific enzymatic reaction with real substances. If you have some data or idea which one to select to this implementation it could be great.
Marek

**Comment by tbeu** [comment]
I once modeled the cellulase protein production as developed by [10.1.1.593.6172.pdf](https://github.com/MarekMatejak/Chemical/files/1678052/10.1.1.593.6172.pdf). Not sure if relevant for you.

https://gist.github.com/tbeu/5ae96059eb7d2aef4bf341a11b6cbe13

**Comment by MarekMatejak** [comment]
I am afraid that I am not able to decode these mathematical relations into the suitable form compatible with any chemical or physical equations. 

E.g. I think that derivation of concentration (as mass m divided by volume V) should not mean the change of substance mass m in case when cellular volume V is changing, because der(m/V) = der(m)/V - m*der(V)/V^2.

**Comment by tbeu** [comment]
Hm, I am confused. I guess we speak about different modeling approaches here. So sorry, just ignore my above comment.
