### ISSUE TITLE
Missing start attribute of log10n

### ISSUE THREAD

**Issue by tbeu** [MarekMatejak/Chemical#5]
Missing start attribute of log10n in Chemical.Components.Substance
```
Warning In Chemical.Examples.SimpleReaction
There is no start attribute of state A.log10n. It is set to 0.
Warning In Chemical.Examples.SimpleReaction
There is no start attribute of state B.log10n. It is set to 0.
```

**Comment by MarekMatejak** [comment]
Hmm, log10n=0 is inconsistent with initial equation. The environment should solve the right value of log10n from the equation amountOfSubstance = 10^log10n in Chemical.Components.Substance, because initial equation is amountOfSubstance=amountOfSubstance_start. So, the start value of log10n must be log10(amountOfSubstance). However I add this expresion to the log10n definition as "Real log10n(start=log10(amountOfSubstance_start))" for sure..

**Comment by tbeu** [comment]
Thanks. Fix confirmed.
